---

# Seleciona flashes por Estado e Município

---

- `OBJETIVO`:
> Este código seleciona os flashes do GLM do satélite GOES-19 de um determinado dia por Estado. Ele também seleciona os flashes de todos os municípios de um mesmo Estado.


- `DADOS DE ENTRADA`:
> Arquivo CSV de flashes acumulados para um determinado dia. Exemplo de nome do arquivo: `flash_glm_goes_2026-09-21.csv`


- `DADOS DE SAÍDA`:
> 1. Tabela com a quantidade de flashes por Estado e por município de um mesmo estado. Exemplo: `flash_counts_by_state_2026-09-21.csv` e `flash_counts_by_municipio_RS_2026-09-21.csv`


- `OBSERVAÇÕES`:
   > Sem observações

- `REALIZADO POR`:
> Enrique V. Mattos - 23/09/2026

- `ATUALIZADO POR`:
> Enrique V. Mattos - 23/09/2026
---

# **1° Passo:** Preparando Ambiente

In [1]:
# instalações
!pip install -q ultraplot cartopy geobr salem rasterio pyproj geopandas descartes

# monta o drive
from google.colab import drive
drive.mount('/content/drive')

# diretório raiz
dir = '/content/drive/MyDrive/2-PESQUISA/0_GLM/estudos_de_caso/2026-09-20e21_FRENTEFRIA_RS'

# diretório de entrada
dir_input = f'{dir}/output/glm_diario_goes'

# diretório de saída
dir_output = f'{dir}/output/glm_figuras_goes'

# importa bibliotecas
import time
import geopandas as gpd
import geobr
import ultraplot as uplt
import cartopy.crs as ccrs
import cartopy.io.shapereader as shpreader
import pandas as pd
from datetime import timedelta, datetime
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LinearSegmentedColormap
import warnings
warnings.filterwarnings("ignore")

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.9/13.9 MB 78.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.5/9.5 MB 92.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.0/53.0 kB 3.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.1/86.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.5/21.5 MB 64.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 83.5/83.5 kB 5.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.1/10.1 MB 87.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 86.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 66.9 MB/s eta 0:00:00
Mounted at /content/drive

# Processa por `Estado`

In [2]:
%%time
#========================================================================================================================#
#                                             LIMITES DO BRASIL
#========================================================================================================================#
# limites do Brasil
lonmin_BR, lonmax_BR, latmin_BR, latmax_BR = -75.0, -33.0, -35.0, 7.0

#========================================================================================================================#
#                                              CARREGA SHAPEFILES
#========================================================================================================================#
# carrega o shapefile dos estados brasileiros. Usa a função read_state do geobr para obter os polígonos dos estados
shapefile_estados = geobr.read_state(year=2020)

#========================================================================================================================#
#                                   LEITURA DO ARQUIVO CSV DIÁRIO DE FLASHES
#========================================================================================================================#
# data
ano, mes, dia = '2026', '09', '21'

# leitura da planilha CSV
if dia == '20': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-20.csv')
if dia == '21': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-21.csv')
if dia == '22': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-22.csv')

# transforma a coluna data para índice do dataframe
df_flash.set_index('time', inplace=True)

# ordena o dataframe
df_flash.sort_index(inplace=True)

#========================================================================================================================#
#                                        SELECIONA OS FLASHES DO BRASIL
#========================================================================================================================#
# seleciona os flashes da região de interesee
df_flash_filtered = df_flash[ (df_flash['lon'] > lonmin_BR) & (df_flash['lon'] < lonmax_BR) & (df_flash['lat'] > latmin_BR) & (df_flash['lat'] < latmax_BR)]

# transforma o dataframe para array
lons_flash_filtered, lats_flash_filtered = df_flash_filtered['lon'].values, df_flash_filtered['lat'].values

#========================================================================================================================#
#                                 EXTRAI OS FLASHES QUE ESTÃO DENTRO DOS ESTADOS
#========================================================================================================================#
# novo geodataframe
df_flash_filtered_gpd = gpd.GeoDataFrame(df_flash_filtered.reset_index(),
                                         geometry = gpd.points_from_xy(df_flash_filtered.lon,
                                                                       df_flash_filtered.lat))

# Dicionário para armazenar o total de flashes por estado
flash_counts_by_state = {}

# Itera sobre cada estado no shapefile_estados
for index, state in shapefile_estados.iterrows():

    print('PROCESSANDO ===>>> ESTADO == ', state['name_state'])

    # Aplica a máscara para o estado atual, garantindo que 'state' seja um GeoDataFrame com CRS
    df_flash_in_state = gpd.overlay(df_flash_filtered_gpd, shapefile_estados.loc[[index]], how='intersection')

    # Conta o número de flashes neste estado
    num_flashes = len(df_flash_in_state)

    # Armazena a contagem no dicionário
    flash_counts_by_state[state['abbrev_state']] = num_flashes
    print('..... TOTAL DE FLASHES = ', num_flashes, '\n')

# colocar num dataframe e imprimir arquivo CSV
df_flash_counts_by_state = pd.DataFrame(list(flash_counts_by_state.items()), columns=['Estado', 'Total de Flashes'])

# organizar do maior para o menor da coluna "Total de Flashes"
df_flash_counts_by_state = df_flash_counts_by_state.sort_values(by='Total de Flashes', ascending=False)

# salvar arquivo CSV
df_flash_counts_by_state.to_csv(f'{dir_output}/flash_counts_by_state_{ano}-{mes}-{dia}.csv', index=False)

# mostra os dados
df_flash_counts_by_state

states_2020_simplified.parquet: 100%|██████████| 1.72M/1.72M [00:00<00:00, 28.7MB/s]

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

PROCESSANDO ===>>> ESTADO ==  Rondônia
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Acre
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Amazonas
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Roraima
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Pará
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Amapá
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Tocantins
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Maranhão
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Piauí
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Ceará
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Rio Grande do Norte
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Paraíba
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Pernambuco
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Alagoas
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Sergipe
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Bahia
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Minas Gerais
..... TOTAL DE FLASHES =  2221

PROCESSANDO ===>>> ESTADO ==  Espírito Santo
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  Rio de Janeiro
..... TOTAL DE FLASHES =  0

PROCESSANDO ===>>> ESTADO ==  São Paulo
..... TOTAL DE FLASHES =  9695

PROCESSANDO ===>>> ESTADO ==  Paraná
..... TOTAL DE FLASHES =  119248

PROCESSANDO ===>>> ESTADO ==  Santa Catarina
..... TOTAL DE FLASHES =  134746

PROCESSANDO ===>>> ESTADO ==  Rio Grande do Sul
..... TOTAL DE FLASHES =  414279

PROCESSANDO ===>>> ESTADO ==  Mato Grosso do Sul
..... TOTAL DE FLASHES =  25815

PROCESSANDO ===>>> ESTADO ==  Mato Grosso
..... TOTAL DE FLASHES =  23926

PROCESSANDO ===>>> ESTADO ==  Goiás
..... TOTAL DE FLASHES =  1586

PROCESSANDO ===>>> ESTADO ==  Distrito Federal
..... TOTAL DE FLASHES =  0

CPU times: user 6min 18s, sys: 1.58 s, total: 6min 19s
Wall time: 6min 34s

   Estado  Total de Flashes
22     RS            414279
21     SC            134746
20     PR            119248
23     MS             25815
24     MT             23926
19     SP              9695
16     MG              2221
25     GO              1586
0      RO                 0
1      AC                 0
2      AM                 0
10     RN                 0
9      CE                 0
8      PI                 0
7      MA                 0
6      TO                 0
5      AP                 0
4      PA                 0
3      RR                 0
18     RJ                 0
17     ES                 0
15     BA                 0
14     SE                 0
12     PE                 0
13     AL                 0
11     PB                 0
26     DF                 0

# Processa por `Município`

In [3]:
%%time
#========================================================================================================================#
#                                             LIMITES DO BRASIL
#========================================================================================================================#
lonmin_BR, lonmax_BR, latmin_BR, latmax_BR = -75.0, -33.0, -35.0, 7.0

#========================================================================================================================#
#                                      ESCOLHA DO ESTADO PELO USUÁRIO
#========================================================================================================================#
# digite a sigla do estado (ex: 'RS', 'SP', 'MS', 'MT', ...)
estado_escolhido = 'RS'   # <-- ALTERE AQUI

# carrega shapefile de todos os estados do Brasil
shapefile_estados = geobr.read_state(year=2020)

# filtra o estado escolhido
shapefile_estado = shapefile_estados[shapefile_estados['abbrev_state'] == estado_escolhido]

if shapefile_estado.empty:
    raise ValueError(f"Estado '{estado_escolhido}' não encontrado. Use a sigla (ex: RS, SP, MS).")

nome_estado = shapefile_estado['name_state'].values[0]
print(f'Estado escolhido: {nome_estado} ({estado_escolhido})')

#========================================================================================================================#
#                               CARREGA MUNICÍPIOS APENAS DO ESTADO ESCOLHIDO
#========================================================================================================================#
# carrega shapefile de municípios do estado escolhido
shapefile_municipios = geobr.read_municipality(year=2020, code_muni=None)

# filtra apenas os municípios do estado escolhido
shapefile_municipios_estado = shapefile_municipios[shapefile_municipios['abbrev_state'] == estado_escolhido].copy()

# total de municípios
tot_muni = len(shapefile_municipios_estado)

print(f'Total de municípios em {nome_estado}: {tot_muni}', '\n')

#========================================================================================================================#
#                                   LEITURA DO ARQUIVO CSV DIÁRIO DE FLASHES
#========================================================================================================================#
ano, mes, dia = '2026', '09', '21'

if dia == '20': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-20.csv')
if dia == '21': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-21.csv')
if dia == '22': df_flash = pd.read_csv(f'{dir_input}/flash_glm_goes_2026-09-22.csv')

df_flash.set_index('time', inplace=True)
df_flash.sort_index(inplace=True)

#========================================================================================================================#
#                                        SELECIONA OS FLASHES DO BRASIL
#========================================================================================================================#
df_flash_filtered = df_flash[ (df_flash['lon'] > lonmin_BR) & (df_flash['lon'] < lonmax_BR) &
                              (df_flash['lat'] > latmin_BR) & (df_flash['lat'] < latmax_BR)]

#========================================================================================================================#
#                                 EXTRAI OS FLASHES QUE ESTÃO DENTRO DOS MUNICÍPIOS
#========================================================================================================================#
# converte para GeoDataFrame
df_flash_filtered_gpd = gpd.GeoDataFrame(df_flash_filtered.reset_index(), geometry=gpd.points_from_xy(df_flash_filtered.lon, df_flash_filtered.lat), crs='EPSG:4326')

# garante mesmo CRS
shapefile_municipios_estado = shapefile_municipios_estado.to_crs(df_flash_filtered_gpd.crs)

# Dicionário para armazenar o total de flashes por município
flash_counts_by_municipio = {}

# Itera sobre cada município do estado escolhido
i=0
for index, muni in shapefile_municipios_estado.iterrows():

    nome_muni = muni['name_muni']
    print(f'[{i+1} de {tot_muni}] ... MUNICÍPIO = {nome_muni}', )

    # interseção dos flashes com o município atual
    df_flash_in_muni = gpd.overlay(df_flash_filtered_gpd, shapefile_municipios_estado.loc[[index]], how='intersection')

    num_flashes = len(df_flash_in_muni)
    flash_counts_by_municipio[nome_muni] = num_flashes
    print(f'{' ' * 15}TOTAL DE FLASHES = {num_flashes}\n')

    i+=1

#========================================================================================================================#
#                                       COLOCA NUM DATAFRAME E SALVA ARQUIVO CSV
#========================================================================================================================#
# monta e ordena a tabela
df_flash_counts_by_municipio = pd.DataFrame(list(flash_counts_by_municipio.items()), columns=['Município', 'Total de Flashes'])
df_flash_counts_by_municipio = df_flash_counts_by_municipio.sort_values(by='Total de Flashes', ascending=False)

# salva CSV
df_flash_counts_by_municipio.to_csv(f'{dir_output}/flash_counts_by_municipio_{estado_escolhido}_{ano}-{mes}-{dia}.csv', index=False)

print(f'\nTotal de relâmpagos por município em {nome_estado}:')
df_flash_counts_by_municipio

Estado escolhido: Rio Grande do Sul (RS)

municipalities_2020_simplified.parquet: 100%|██████████| 20.2M/20.2M [00:00<00:00, 70.1MB/s]

Total de municípios em Rio Grande do Sul: 497

[1 de 497] ... MUNICÍPIO = Aceguá
               TOTAL DE FLASHES = 1799

[2 de 497] ... MUNICÍPIO = Água Santa
               TOTAL DE FLASHES = 158

[3 de 497] ... MUNICÍPIO = Agudo
               TOTAL DE FLASHES = 1431

[4 de 497] ... MUNICÍPIO = Ajuricaba
               TOTAL DE FLASHES = 204

[5 de 497] ... MUNICÍPIO = Alecrim
               TOTAL DE FLASHES = 3

[6 de 497] ... MUNICÍPIO = Alegrete
               TOTAL DE FLASHES = 7459

[7 de 497] ... MUNICÍPIO = Alegria
               TOTAL DE FLASHES = 34

[8 de 497] ... MUNICÍPIO = Almirante Tamandaré do Sul
               TOTAL DE FLASHES = 373

[9 de 497] ... MUNICÍPIO = Alpestre
               TOTAL DE FLASHES = 354

[10 de 497] ... MUNICÍPIO = Alto Alegre
               TOTAL DE FLASHES = 330

[11 de 497] ... MUNICÍPIO = Alto Feliz
               TOTAL DE FLASHES = 189

[12 de 497] ... MUNICÍPIO = Alvorada
               TOTAL DE FLASHES = 111

[13 de 497] ... MUNICÍPIO = Amaral Ferrador
               TOTAL DE FLASHES = 358

[14 de 497] ... MUNICÍPIO = Ametista do Sul
               TOTAL DE FLASHES = 47

[15 de 497] ... MUNICÍPIO = André da Rocha
               TOTAL DE FLASHES = 303

[16 de 497] ... MUNICÍPIO = Anta Gorda
               TOTAL DE FLASHES = 664

[17 de 497] ... MUNICÍPIO = Antônio Prado
               TOTAL DE FLASHES = 1088

[18 de 497] ... MUNICÍPIO = Arambaré
               TOTAL DE FLASHES = 359

[19 de 497] ... MUNICÍPIO = Araricá
               TOTAL DE FLASHES = 40

[20 de 497] ... MUNICÍPIO = Aratiba
               TOTAL DE FLASHES = 325

[21 de 497] ... MUNICÍPIO = Arroio do Meio
               TOTAL DE FLASHES = 339

[22 de 497] ... MUNICÍPIO = Arroio do Sal
               TOTAL DE FLASHES = 59

[23 de 497] ... MUNICÍPIO = Arroio do Padre
               TOTAL DE FLASHES = 120

[24 de 497] ... MUNICÍPIO = Arroio dos Ratos
               TOTAL DE FLASHES = 616

[25 de 497] ... MUNICÍPIO = Arroio do Tigre
               TOTAL DE FLASHES = 813

[26 de 497] ... MUNICÍPIO = Arroio Grande
               TOTAL DE FLASHES = 2066

[27 de 497] ... MUNICÍPIO = Arvorezinha
               TOTAL DE FLASHES = 647

[28 de 497] ... MUNICÍPIO = Augusto Pestana
               TOTAL DE FLASHES = 926

[29 de 497] ... MUNICÍPIO = Áurea
               TOTAL DE FLASHES = 231

[30 de 497] ... MUNICÍPIO = Bagé
               TOTAL DE FLASHES = 4141

[31 de 497] ... MUNICÍPIO = Balneário Pinhal
               TOTAL DE FLASHES = 77

[32 de 497] ... MUNICÍPIO = Barão
               TOTAL DE FLASHES = 235

[33 de 497] ... MUNICÍPIO = Barão de Cotegipe
               TOTAL DE FLASHES = 857

[34 de 497] ... MUNICÍPIO = Barão do Triunfo
               TOTAL DE FLASHES = 425

[35 de 497] ... MUNICÍPIO = Barracão
               TOTAL DE FLASHES = 844

[36 de 497] ... MUNICÍPIO = Barra do Guarita
               TOTAL DE FLASHES = 50

[37 de 497] ... MUNICÍPIO = Barra do Quaraí
               TOTAL DE FLASHES = 23

[38 de 497] ... MUNICÍPIO = Barra do Ribeiro
               TOTAL DE FLASHES = 579

[39 de 497] ... MUNICÍPIO = Barra do Rio Azul
               TOTAL DE FLASHES = 142

[40 de 497] ... MUNICÍPIO = Barra Funda
               TOTAL DE FLASHES = 32

[41 de 497] ... MUNICÍPIO = Barros Cassal
               TOTAL DE FLASHES = 1206

[42 de 497] ... MUNICÍPIO = Benjamin Constant do Sul
               TOTAL DE FLASHES = 226

[43 de 497] ... MUNICÍPIO = Bento Gonçalves
               TOTAL DE FLASHES = 921

[44 de 497] ... MUNICÍPIO = Boa Vista das Missões
               TOTAL DE FLASHES = 30

[45 de 497] ... MUNICÍPIO = Boa Vista do Buricá
               TOTAL DE FLASHES = 26

[46 de 497] ... MUNICÍPIO = Boa Vista do Cadeado
               TOTAL DE FLASHES = 2188

[47 de 497] ... MUNICÍPIO = Boa Vista do Incra
               TOTAL DE FLASHES = 2572

[48 de 497] ... MUNICÍPIO = Boa Vista do Sul
               TOTAL DE FLASHES = 168

[49 de 497] ... MUNICÍPIO = Bom Jesus
               TOTAL DE FLASHES = 7552

[50 de 497] ... MUNICÍPIO = Bom Princípio
               TOTAL DE FLASHES = 111

[51 de 497] ... MUNICÍPIO = Bom Progresso
               TOTAL DE FLASHES = 13

[52 de 497] ... MUNICÍPIO = Bom Retiro do Sul
               TOTAL DE FLASHES = 162

[53 de 497] ... MUNICÍPIO = Boqueirão do Leão
               TOTAL DE FLASHES = 989

[54 de 497] ... MUNICÍPIO = Bossoroca
               TOTAL DE FLASHES = 562

[55 de 497] ... MUNICÍPIO = Bozano
               TOTAL DE FLASHES = 144

[56 de 497] ... MUNICÍPIO = Braga
               TOTAL DE FLASHES = 30

[57 de 497] ... MUNICÍPIO = Brochier
               TOTAL DE FLASHES = 181

[58 de 497] ... MUNICÍPIO = Butiá
               TOTAL DE FLASHES = 1071

[59 de 497] ... MUNICÍPIO = Caçapava do Sul
               TOTAL DE FLASHES = 4029

[60 de 497] ... MUNICÍPIO = Cacequi
               TOTAL DE FLASHES = 7976

[61 de 497] ... MUNICÍPIO = Cachoeira do Sul
               TOTAL DE FLASHES = 7912

[62 de 497] ... MUNICÍPIO = Cachoeirinha
               TOTAL DE FLASHES = 22

[63 de 497] ... MUNICÍPIO = Cacique Doble
               TOTAL DE FLASHES = 470

[64 de 497] ... MUNICÍPIO = Caibaté
               TOTAL DE FLASHES = 192

[65 de 497] ... MUNICÍPIO = Caiçara
               TOTAL DE FLASHES = 217

[66 de 497] ... MUNICÍPIO = Camaquã
               TOTAL DE FLASHES = 1028

[67 de 497] ... MUNICÍPIO = Camargo
               TOTAL DE FLASHES = 466

[68 de 497] ... MUNICÍPIO = Cambará do Sul
               TOTAL DE FLASHES = 2011

[69 de 497] ... MUNICÍPIO = Campestre da Serra
               TOTAL DE FLASHES = 755

[70 de 497] ... MUNICÍPIO = Campina das Missões
               TOTAL DE FLASHES = 35

[71 de 497] ... MUNICÍPIO = Campinas do Sul
               TOTAL DE FLASHES = 278

[72 de 497] ... MUNICÍPIO = Campo Bom
               TOTAL DE FLASHES = 52

[73 de 497] ... MUNICÍPIO = Campo Novo
               TOTAL DE FLASHES = 264

[74 de 497] ... MUNICÍPIO = Campos Borges
               TOTAL DE FLASHES = 690

[75 de 497] ... MUNICÍPIO = Candelária
               TOTAL DE FLASHES = 2260

[76 de 497] ... MUNICÍPIO = Cândido Godói
               TOTAL DE FLASHES = 21

[77 de 497] ... MUNICÍPIO = Candiota
               TOTAL DE FLASHES = 925

[78 de 497] ... MUNICÍPIO = Canela
               TOTAL DE FLASHES = 243

[79 de 497] ... MUNICÍPIO = Canguçu
               TOTAL DE FLASHES = 3559

[80 de 497] ... MUNICÍPIO = Canoas
               TOTAL DE FLASHES = 154

[81 de 497] ... MUNICÍPIO = Canudos do Vale
               TOTAL DE FLASHES = 229

[82 de 497] ... MUNICÍPIO = Capão Bonito do Sul
               TOTAL DE FLASHES = 796

[83 de 497] ... MUNICÍPIO = Capão da Canoa
               TOTAL DE FLASHES = 70

[84 de 497] ... MUNICÍPIO = Capão do Cipó
               TOTAL DE FLASHES = 1136

[85 de 497] ... MUNICÍPIO = Capão do Leão
               TOTAL DE FLASHES = 646

[86 de 497] ... MUNICÍPIO = Capivari do Sul
               TOTAL DE FLASHES = 219

[87 de 497] ... MUNICÍPIO = Capela de Santana
               TOTAL DE FLASHES = 292

[88 de 497] ... MUNICÍPIO = Capitão
               TOTAL DE FLASHES = 197

[89 de 497] ... MUNICÍPIO = Carazinho
               TOTAL DE FLASHES = 744

[90 de 497] ... MUNICÍPIO = Caraá
               TOTAL DE FLASHES = 198

[91 de 497] ... MUNICÍPIO = Carlos Barbosa
               TOTAL DE FLASHES = 513

[92 de 497] ... MUNICÍPIO = Carlos Gomes
               TOTAL DE FLASHES = 132

[93 de 497] ... MUNICÍPIO = Casca
               TOTAL DE FLASHES = 430

[94 de 497] ... MUNICÍPIO = Caseiros
               TOTAL DE FLASHES = 247

[95 de 497] ... MUNICÍPIO = Catuípe
               TOTAL DE FLASHES = 321

[96 de 497] ... MUNICÍPIO = Caxias do Sul
               TOTAL DE FLASHES = 5181

[97 de 497] ... MUNICÍPIO = Centenário
               TOTAL DE FLASHES = 188

[98 de 497] ... MUNICÍPIO = Cerrito
               TOTAL DE FLASHES = 206

[99 de 497] ... MUNICÍPIO = Cerro Branco
               TOTAL DE FLASHES = 354

[100 de 497] ... MUNICÍPIO = Cerro Grande
               TOTAL DE FLASHES = 29

[101 de 497] ... MUNICÍPIO = Cerro Grande do Sul
               TOTAL DE FLASHES = 263

[102 de 497] ... MUNICÍPIO = Cerro Largo
               TOTAL DE FLASHES = 162

[103 de 497] ... MUNICÍPIO = Chapada
               TOTAL DE FLASHES = 517

[104 de 497] ... MUNICÍPIO = Charqueadas
               TOTAL DE FLASHES = 207

[105 de 497] ... MUNICÍPIO = Charrua
               TOTAL DE FLASHES = 275

[106 de 497] ... MUNICÍPIO = Chiapetta
               TOTAL DE FLASHES = 73

[107 de 497] ... MUNICÍPIO = Chuí
               TOTAL DE FLASHES = 19

[108 de 497] ... MUNICÍPIO = Chuvisca
               TOTAL DE FLASHES = 157

[109 de 497] ... MUNICÍPIO = Cidreira
               TOTAL DE FLASHES = 119

[110 de 497] ... MUNICÍPIO = Ciríaco
               TOTAL DE FLASHES = 117

[111 de 497] ... MUNICÍPIO = Colinas
               TOTAL DE FLASHES = 98

[112 de 497] ... MUNICÍPIO = Colorado
               TOTAL DE FLASHES = 700

[113 de 497] ... MUNICÍPIO = Condor
               TOTAL DE FLASHES = 588

[114 de 497] ... MUNICÍPIO = Constantina
               TOTAL DE FLASHES = 144

[115 de 497] ... MUNICÍPIO = Coqueiro Baixo
               TOTAL DE FLASHES = 308

[116 de 497] ... MUNICÍPIO = Coqueiros do Sul
               TOTAL DE FLASHES = 342

[117 de 497] ... MUNICÍPIO = Coronel Barros
               TOTAL DE FLASHES = 112

[118 de 497] ... MUNICÍPIO = Coronel Bicaco
               TOTAL DE FLASHES = 433

[119 de 497] ... MUNICÍPIO = Coronel Pilar
               TOTAL DE FLASHES = 320

[120 de 497] ... MUNICÍPIO = Cotiporã
               TOTAL DE FLASHES = 414

[121 de 497] ... MUNICÍPIO = Coxilha
               TOTAL DE FLASHES = 227

[122 de 497] ... MUNICÍPIO = Crissiumal
               TOTAL DE FLASHES = 226

[123 de 497] ... MUNICÍPIO = Cristal
               TOTAL DE FLASHES = 412

[124 de 497] ... MUNICÍPIO = Cristal do Sul
               TOTAL DE FLASHES = 113

[125 de 497] ... MUNICÍPIO = Cruz Alta
               TOTAL DE FLASHES = 4343

[126 de 497] ... MUNICÍPIO = Cruzaltense
               TOTAL DE FLASHES = 152

[127 de 497] ... MUNICÍPIO = Cruzeiro do Sul
               TOTAL DE FLASHES = 319

[128 de 497] ... MUNICÍPIO = David Canabarro
               TOTAL DE FLASHES = 125

[129 de 497] ... MUNICÍPIO = Derrubadas
               TOTAL DE FLASHES = 157

[130 de 497] ... MUNICÍPIO = Dezesseis de Novembro
               TOTAL DE FLASHES = 38

[131 de 497] ... MUNICÍPIO = Dilermando de Aguiar
               TOTAL DE FLASHES = 2782

[132 de 497] ... MUNICÍPIO = Dois Irmãos
               TOTAL DE FLASHES = 53

[133 de 497] ... MUNICÍPIO = Dois Irmãos das Missões
               TOTAL DE FLASHES = 79

[134 de 497] ... MUNICÍPIO = Dois Lajeados
               TOTAL DE FLASHES = 373

[135 de 497] ... MUNICÍPIO = Dom Feliciano
               TOTAL DE FLASHES = 1633

[136 de 497] ... MUNICÍPIO = Dom Pedro de Alcântara
               TOTAL DE FLASHES = 34

[137 de 497] ... MUNICÍPIO = Dom Pedrito
               TOTAL DE FLASHES = 5299

[138 de 497] ... MUNICÍPIO = Dona Francisca
               TOTAL DE FLASHES = 439

[139 de 497] ... MUNICÍPIO = Doutor Maurício Cardoso
               TOTAL DE FLASHES = 71

[140 de 497] ... MUNICÍPIO = Doutor Ricardo
               TOTAL DE FLASHES = 376

[141 de 497] ... MUNICÍPIO = Eldorado do Sul
               TOTAL DE FLASHES = 622

[142 de 497] ... MUNICÍPIO = Encantado
               TOTAL DE FLASHES = 437

[143 de 497] ... MUNICÍPIO = Encruzilhada do Sul
               TOTAL DE FLASHES = 3570

[144 de 497] ... MUNICÍPIO = Engenho Velho
               TOTAL DE FLASHES = 60

[145 de 497] ... MUNICÍPIO = Entre-Ijuís
               TOTAL DE FLASHES = 798

[146 de 497] ... MUNICÍPIO = Entre Rios do Sul
               TOTAL DE FLASHES = 345

[147 de 497] ... MUNICÍPIO = Erebango
               TOTAL DE FLASHES = 188

[148 de 497] ... MUNICÍPIO = Erechim
               TOTAL DE FLASHES = 825

[149 de 497] ... MUNICÍPIO = Ernestina
               TOTAL DE FLASHES = 435

[150 de 497] ... MUNICÍPIO = Herval
               TOTAL DE FLASHES = 1567

[151 de 497] ... MUNICÍPIO = Erval Grande
               TOTAL DE FLASHES = 289

[152 de 497] ... MUNICÍPIO = Erval Seco
               TOTAL DE FLASHES = 203

[153 de 497] ... MUNICÍPIO = Esmeralda
               TOTAL DE FLASHES = 1322

[154 de 497] ... MUNICÍPIO = Esperança do Sul
               TOTAL DE FLASHES = 14

[155 de 497] ... MUNICÍPIO = Espumoso
               TOTAL DE FLASHES = 2301

[156 de 497] ... MUNICÍPIO = Estação
               TOTAL DE FLASHES = 316

[157 de 497] ... MUNICÍPIO = Estância Velha
               TOTAL DE FLASHES = 42

[158 de 497] ... MUNICÍPIO = Esteio
               TOTAL DE FLASHES = 16

[159 de 497] ... MUNICÍPIO = Estrela
               TOTAL DE FLASHES = 378

[160 de 497] ... MUNICÍPIO = Estrela Velha
               TOTAL DE FLASHES = 565

[161 de 497] ... MUNICÍPIO = Eugênio de Castro
               TOTAL DE FLASHES = 792

[162 de 497] ... MUNICÍPIO = Fagundes Varela
               TOTAL DE FLASHES = 246

[163 de 497] ... MUNICÍPIO = Farroupilha
               TOTAL DE FLASHES = 1301

[164 de 497] ... MUNICÍPIO = Faxinal do Soturno
               TOTAL DE FLASHES = 469

[165 de 497] ... MUNICÍPIO = Faxinalzinho
               TOTAL DE FLASHES = 140

[166 de 497] ... MUNICÍPIO = Fazenda Vilanova
               TOTAL DE FLASHES = 137

[167 de 497] ... MUNICÍPIO = Feliz
               TOTAL DE FLASHES = 142

[168 de 497] ... MUNICÍPIO = Flores da Cunha
               TOTAL DE FLASHES = 1056

[169 de 497] ... MUNICÍPIO = Floriano Peixoto
               TOTAL DE FLASHES = 219

[170 de 497] ... MUNICÍPIO = Fontoura Xavier
               TOTAL DE FLASHES = 1088

[171 de 497] ... MUNICÍPIO = Formigueiro
               TOTAL DE FLASHES = 1932

[172 de 497] ... MUNICÍPIO = Forquetinha
               TOTAL DE FLASHES = 236

[173 de 497] ... MUNICÍPIO = Fortaleza dos Valos
               TOTAL DE FLASHES = 2871

[174 de 497] ... MUNICÍPIO = Frederico Westphalen
               TOTAL DE FLASHES = 364

[175 de 497] ... MUNICÍPIO = Garibaldi
               TOTAL DE FLASHES = 662

[176 de 497] ... MUNICÍPIO = Garruchos
               TOTAL DE FLASHES = 78

[177 de 497] ... MUNICÍPIO = Gaurama
               TOTAL DE FLASHES = 315

[178 de 497] ... MUNICÍPIO = General Câmara
               TOTAL DE FLASHES = 832

[179 de 497] ... MUNICÍPIO = Gentil
               TOTAL DE FLASHES = 45

[180 de 497] ... MUNICÍPIO = Getúlio Vargas
               TOTAL DE FLASHES = 368

[181 de 497] ... MUNICÍPIO = Giruá
               TOTAL DE FLASHES = 192

[182 de 497] ... MUNICÍPIO = Glorinha
               TOTAL DE FLASHES = 187

[183 de 497] ... MUNICÍPIO = Gramado
               TOTAL DE FLASHES = 301

[184 de 497] ... MUNICÍPIO = Gramado dos Loureiros
               TOTAL DE FLASHES = 350

[185 de 497] ... MUNICÍPIO = Gramado Xavier
               TOTAL DE FLASHES = 683

[186 de 497] ... MUNICÍPIO = Gravataí
               TOTAL DE FLASHES = 357

[187 de 497] ... MUNICÍPIO = Guabiju
               TOTAL DE FLASHES = 136

[188 de 497] ... MUNICÍPIO = Guaíba
               TOTAL DE FLASHES = 445

[189 de 497] ... MUNICÍPIO = Guaporé
               TOTAL DE FLASHES = 729

[190 de 497] ... MUNICÍPIO = Guarani das Missões
               TOTAL DE FLASHES = 237

[191 de 497] ... MUNICÍPIO = Harmonia
               TOTAL DE FLASHES = 70

[192 de 497] ... MUNICÍPIO = Herveiras
               TOTAL DE FLASHES = 249

[193 de 497] ... MUNICÍPIO = Horizontina
               TOTAL DE FLASHES = 36

[194 de 497] ... MUNICÍPIO = Hulha Negra
               TOTAL DE FLASHES = 888

[195 de 497] ... MUNICÍPIO = Humaitá
               TOTAL DE FLASHES = 79

[196 de 497] ... MUNICÍPIO = Ibarama
               TOTAL DE FLASHES = 738

[197 de 497] ... MUNICÍPIO = Ibiaçá
               TOTAL DE FLASHES = 516

[198 de 497] ... MUNICÍPIO = Ibiraiaras
               TOTAL DE FLASHES = 272

[199 de 497] ... MUNICÍPIO = Ibirapuitã
               TOTAL DE FLASHES = 762

[200 de 497] ... MUNICÍPIO = Ibirubá
               TOTAL DE FLASHES = 1568

[201 de 497] ... MUNICÍPIO = Igrejinha
               TOTAL DE FLASHES = 118

[202 de 497] ... MUNICÍPIO = Ijuí
               TOTAL DE FLASHES = 384

[203 de 497] ... MUNICÍPIO = Ilópolis
               TOTAL DE FLASHES = 352

[204 de 497] ... MUNICÍPIO = Imbé
               TOTAL DE FLASHES = 24

[205 de 497] ... MUNICÍPIO = Imigrante
               TOTAL DE FLASHES = 165

[206 de 497] ... MUNICÍPIO = Independência
               TOTAL DE FLASHES = 25

[207 de 497] ... MUNICÍPIO = Inhacorá
               TOTAL DE FLASHES = 21

[208 de 497] ... MUNICÍPIO = Ipê
               TOTAL DE FLASHES = 837

[209 de 497] ... MUNICÍPIO = Ipiranga do Sul
               TOTAL DE FLASHES = 366

[210 de 497] ... MUNICÍPIO = Iraí
               TOTAL DE FLASHES = 321

[211 de 497] ... MUNICÍPIO = Itaara
               TOTAL DE FLASHES = 476

[212 de 497] ... MUNICÍPIO = Itacurubi
               TOTAL DE FLASHES = 308

[213 de 497] ... MUNICÍPIO = Itapuca
               TOTAL DE FLASHES = 481

[214 de 497] ... MUNICÍPIO = Itaqui
               TOTAL DE FLASHES = 4830

[215 de 497] ... MUNICÍPIO = Itati
               TOTAL DE FLASHES = 120

[216 de 497] ... MUNICÍPIO = Itatiba do Sul
               TOTAL DE FLASHES = 235

[217 de 497] ... MUNICÍPIO = Ivorá
               TOTAL DE FLASHES = 192

[218 de 497] ... MUNICÍPIO = Ivoti
               TOTAL DE FLASHES = 126

[219 de 497] ... MUNICÍPIO = Jaboticaba
               TOTAL DE FLASHES = 33

[220 de 497] ... MUNICÍPIO = Jacuizinho
               TOTAL DE FLASHES = 920

[221 de 497] ... MUNICÍPIO = Jacutinga
               TOTAL DE FLASHES = 199

[222 de 497] ... MUNICÍPIO = Jaguarão
               TOTAL DE FLASHES = 1829

[223 de 497] ... MUNICÍPIO = Jaguari
               TOTAL DE FLASHES = 3296

[224 de 497] ... MUNICÍPIO = Jaquirana
               TOTAL DE FLASHES = 2966

[225 de 497] ... MUNICÍPIO = Jari
               TOTAL DE FLASHES = 3524

[226 de 497] ... MUNICÍPIO = Jóia
               TOTAL DE FLASHES = 2319

[227 de 497] ... MUNICÍPIO = Júlio de Castilhos
               TOTAL DE FLASHES = 4845

[228 de 497] ... MUNICÍPIO = Lagoa Bonita do Sul
               TOTAL DE FLASHES = 207

[229 de 497] ... MUNICÍPIO = Lagoão
               TOTAL DE FLASHES = 919

[230 de 497] ... MUNICÍPIO = Lagoa dos Três Cantos
               TOTAL DE FLASHES = 496

[231 de 497] ... MUNICÍPIO = Lagoa Vermelha
               TOTAL DE FLASHES = 1761

[232 de 497] ... MUNICÍPIO = Lajeado
               TOTAL DE FLASHES = 287

[233 de 497] ... MUNICÍPIO = Lajeado do Bugre
               TOTAL DE FLASHES = 9

[234 de 497] ... MUNICÍPIO = Lavras do Sul
               TOTAL DE FLASHES = 3086

[235 de 497] ... MUNICÍPIO = Liberato Salzano
               TOTAL DE FLASHES = 194

[236 de 497] ... MUNICÍPIO = Lindolfo Collor
               TOTAL DE FLASHES = 58

[237 de 497] ... MUNICÍPIO = Linha Nova
               TOTAL DE FLASHES = 116

[238 de 497] ... MUNICÍPIO = Machadinho
               TOTAL DE FLASHES = 470

[239 de 497] ... MUNICÍPIO = Maçambará
               TOTAL DE FLASHES = 3399

[240 de 497] ... MUNICÍPIO = Mampituba
               TOTAL DE FLASHES = 69

[241 de 497] ... MUNICÍPIO = Manoel Viana
               TOTAL DE FLASHES = 5244

[242 de 497] ... MUNICÍPIO = Maquiné
               TOTAL DE FLASHES = 415

[243 de 497] ... MUNICÍPIO = Maratá
               TOTAL DE FLASHES = 130

[244 de 497] ... MUNICÍPIO = Marau
               TOTAL DE FLASHES = 833

[245 de 497] ... MUNICÍPIO = Marcelino Ramos
               TOTAL DE FLASHES = 236

[246 de 497] ... MUNICÍPIO = Mariana Pimentel
               TOTAL DE FLASHES = 372

[247 de 497] ... MUNICÍPIO = Mariano Moro
               TOTAL DE FLASHES = 55

[248 de 497] ... MUNICÍPIO = Marques de Souza
               TOTAL DE FLASHES = 360

[249 de 497] ... MUNICÍPIO = Mata
               TOTAL DE FLASHES = 1319

[250 de 497] ... MUNICÍPIO = Mato Castelhano
               TOTAL DE FLASHES = 56


                  Município  Total de Flashes
368  Sant'ana do Livramento             13521
385             São Gabriel             12926
383  São Francisco de Assis             12595
372                Santiago              8822
59                  Cacequi              7976
..                      ...               ...
326            Porto Lucena                 4
4                   Alecrim                 3
463               Tucunduva                 2
327              Porto Mauá                 0
328         Porto Vera Cruz                 0

[497 rows x 2 columns]